#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"<<-EOSQL
  CREATE USER $LOCAL_POSTGRES_USER WITH SUPERUSER PASSWORD '$SUPERUSER_PASSWORD';
  CREATE USER dbt WITH PASSWORD '$DBT_PASSWORD';
  CREATE USER ecs WITH PASSWORD '$ECW_PASSWORD';

  CREATE SCHEMA IF NOT EXISTS raw;
  CREATE SCHEMA IF NOT EXISTS analytics_dev;
  CREATE SCHEMA IF NOT EXISTS analytics;
  CREATE SCHEMA IF NOT EXISTS ecs_logs;

  GRANT CONNECT ON DATABASE warehouse TO dbt;
  GRANT CONNECT ON DATABASE warehouse TO ecs;

  GRANT USAGE ON SCHEMA raw TO dbt;
  GRANT ALL PRIVILEGES ON SCHEMA analytics_dev TO dbt;
  GRANT ALL PRIVILEGES ON SCHEMA analytics TO dbt;

  GRANT SELECT ON ALL TABLES IN SCHEMA raw TO dbt;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics TO dbt;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics_dev TO dbt;

  ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT ON TABLES TO dbt;
  ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL PRIVILEGES ON TABLES TO dbt;
  ALTER DEFAULT PRIVILEGES IN SCHEMA analytics_dev GRANT ALL PRIVILEGES ON TABLES TO dbt;

  GRANT USAGE ON SCHEMA raw TO ecs;
  GRANT ALL PRIVILEGES ON SCHEMA analytics_dev TO ecs;
  GRANT ALL PRIVILEGES ON SCHEMA analytics TO ecs;
  GRANT ALL PRIVILEGES ON SCHEMA ecs_logs TO ecs;

  GRANT SELECT ON ALL TABLES IN SCHEMA raw TO ecs;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics TO ecs;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics_dev TO ecs;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ecs_logs TO ecs;

  ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT ON TABLES TO ecs;
  ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL PRIVILEGES ON TABLES TO ecs;
  ALTER DEFAULT PRIVILEGES IN SCHEMA analytics_dev GRANT ALL PRIVILEGES ON TABLES TO ecs;
  ALTER DEFAULT PRIVILEGES IN SCHEMA ecs_logs GRANT ALL PRIVILEGES ON TABLES TO ecs;
EOSQL
